ci: Back to OSV scanner

diff --git a/.github/workflows/build-dev.yaml b/.github/workflows/build-dev.yaml
--- a/.github/workflows/build-dev.yaml
+++ b/.github/workflows/build-dev.yaml
@@ -90,25 +90,23 @@ jobs:
       with:
         context: .
         tags: ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
-    - name: Run Trivy vulnerability scanner
-      # Here we scan for library problems only,
-      # we're not interested in 'os' issues.
+    - name: Vulnerability Scan (OSV)
+      # The vulnerability scan (using Google's OSV)
+      # Allowed to fail (we force true) as it's used for information only
+      # The generated "Common Vulnerability Scoring System (CVSS)"" values
+      # are interpreted as...
       #
-      # We also use a custom 'markdown.tpl' template because trivy
-      # cannot output markdown (!). The template is located in our repository's
-      # 'trivy/templates' directory. The next step outputs this markdown
-      # to the GitHub step summary.
-      # (see https://teknologi.nl/posts/proactivesecuritytrivy/)
-      uses: aquasecurity/trivy-action@0.33.1
-      with:
-        image-ref: ${{ steps.vars.outputs.BE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }}
-        version: latest
-        vuln-type: library
-        scanners: vuln
-        severity: CRITICAL,HIGH
-        format: template
-        template: "@${{ github.workspace }}/trivy/templates/markdown.tpl"
-        output: trivy-results.md
+      # - None: 0.0 (No impact)
+      # - Low: 0.1–3.9 (Minor risk)
+      # - Medium: 4.0–6.9 (Moderate risk)
+      # - High: 7.0–8.9 (Serious risk)
+      # - Critical: 9.0–10.0 (Grave, severe risk)
+      run: |
+        wget https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64 -O osv-scanner
+        chmod +x osv-scanner
+        ./osv-scanner scan image ${{ steps.vars.outputs.FE_NAMESPACE }}/fragalysis-backend:${{ env.GITHUB_REF_SLUG }} \
+            --format markdown --output scan.md || true
+        cat scan.md >> $GITHUB_STEP_SUMMARY
     - name: Output Trivy Results to step summary
       run: |
         cat trivy-results.md >> $GITHUB_STEP_SUMMARY
